### ISSUE TITLE
Selecting a recipe freezes other clients in multiplayer

### ISSUE THREAD

**Issue by sultanakaneel** [Helfima/helmod#160]
Whenever I add a recipe. Everyone else freezes for a second. Probably caused by having too many recipes loaded into the filter at once. (playing with bob's and pyanodons). Any way to alleviate this?

**Comment by silverneko** [comment]
I second that. I've played with a Bob&Angel's map and a pyanodon's full suite map and everytime the recipe selection popup shows up everybody starts to lag.

**Comment by Helfima** [comment]
I will try to separate the steps of the mod on several ticks

**Comment by maca134** [comment]
at the moment, when using the mod at all i get desync'ed/dc'ed from my server (private for a couple of friends). Running bobs+angels

**Comment by AquilaSagitta** [comment]
> I will try to separate the steps of the mod on several ticks

Have you tried cacheing the recipes? They don't change once games started so you could just cache the recipes on first access then use that copy from then on. Should greatly speed up adding recipes to blocks/production lines

**Comment by maca134** [comment]
oddly it is only happening when running a dedicated server. If i run a "local" mp game no problems.
How would i cache the recipes, havnt seen any option for it.

**Comment by Oaquasis** [comment]
I do not know what the implications would be, but would it be a solution not to load disabled recipes by default? Mid-game with Angel's and Bob's this reduces the load time drastically on my save.

The current method:
```lua 
function RecipeSelector.methods:updateGroups(item, item2, item3)
Logging:trace(self:classname(), "updateGroups():", item, item2, item3)
  local global_player = Player.getGlobal()
  local global_gui = Player.getGlobalGui()
  -- recuperation recipes
  local list_group = {}
  local list_subgroup = {}
  local list_prototype = {}

  firstGroup = nil
  for key, recipe in pairs(Player.getRecipes()) do
    self:appendGroups(recipe.name, "recipe", list_group, list_subgroup, list_prototype)
  end

...
```

Proposed method:
```lua 
function RecipeSelector.methods:updateGroups(item, item2, item3)
Logging:trace(self:classname(), "updateGroups():", item, item2, item3)
  local global_player = Player.getGlobal()
  local global_gui = Player.getGlobalGui()

  local filter_show_disable = Player.getGlobalSettings("filter_show_disable")
  local filter_show_hidden = Player.getGlobalSettings("filter_show_hidden")

  -- recuperation recipes
  local list_group = {}
  local list_subgroup = {}
  local list_prototype = {}

  firstGroup = nil
  for key, recipe in pairs(Player.getRecipes()) do
    if recipe.enabled == true or filter_show_disable == true then
      self:appendGroups(recipe.name, "recipe", list_group, list_subgroup, list_prototype)
    end
  end

...
```

Another possibilty I see is in the appendGroups method of the selector and that is to move the "load" inside the If statements

```Lua
function RecipeSelector.methods:appendGroups(name, type, list_group, list_subgroup, list_prototype)
  Logging:trace(self:classname(), "appendGroups()", name, type)
  RecipePrototype.load(name, type) -- <<<<<<<<<<<  THIS
  local find = self:checkFilter(RecipePrototype)
  local filter_show_disable = Player.getGlobalSettings("filter_show_disable")
  local filter_show_hidden = Player.getGlobalSettings("filter_show_hidden")

  if
    find == true and (RecipePrototype.getEnabled() == true or filter_show_disable == true) and
      (RecipePrototype.getHidden() == false or filter_show_hidden == true)
   then
    -- <<<<<<<<<<<<<<< TO HERE
    local lua_recipe = RecipePrototype.native()
    local group_name = lua_recipe.group.name
    local subgroup_name = lua_recipe.subgroup.name

    if firstGroup == nil then
      firstGroup = group_name
    end
    list_group[group_name] = lua_recipe.group
    list_subgroup[subgroup_name] = lua_recipe.subgroup
    if list_prototype[group_name] == nil then
      list_prototype[group_name] = {}
    end
    if list_prototype[group_name][subgroup_name] == nil then
      list_prototype[group_name][subgroup_name] = {}
    end
    table.insert(list_prototype[group_name][subgroup_name], {name = name, type = type, order = lua_recipe.order})
  end
end
```

I think moving the entire filter to the updateGroups method might be the better solution, as the appendGroups method should not be called for recipes that are not displayed.

**Comment by Helfima** [comment]
Fixed in Version 0.8.4

**Comment by Helfima** [comment]
oups is not Fixed in Version 0.8.4

**Comment by Helfima** [comment]
I have make a v0.8.7
normaly is 50% faster and the process run on 2 ticks

**Comment by Helfima** [comment]
more faster in v0.8.10

**Comment by taylorthurlow** [comment]
This still happens on 0.10.9. I don't have any desync/lag issues, but the server pauses whenever I'm in the recipe selection menu.
