### ISSUE TITLE
Products linked broken

### ISSUE THREAD

**Issue by Helfima** [Helfima/helmod#516]
![image](https://github.com/Helfima/helmod/assets/20326713/1da6b038-27b4-4165-9e4e-1f17651769d3)
rework calculation block by block ?

**Comment by SerhiyShamshetdinov** [comment]
Just to remember in the same topic:

1) Looks like: by-product of the block from tree level 3 **never** is linked to requested one at level 2 (root is 1):
https://discord.com/channels/676795981437599765/676798501753192509/1220467638619209830

2) There is no way to control output by-product linking inside the block: Ctrl-click works the same as click - it opens input for overproduction amount:
https://discord.com/channels/676795981437599765/676797589659713586/1218650690101182524

3) The block (contrarily to recipe) has no control on selecting primary output product ("+" marking) and on detaching by-product ("-" mark, I never used). So: no way to tell to resolver what is a primary product to use in calculations.

4) For unlinked block at _root level_: it's by-product is **always linked** to upper block requested amount:
https://discord.com/channels/676795981437599765/676798501753192509/1220504215617540147

**Comment by Helfima** [comment]
I found a complex solution
In this example I have 3 blocks, the B bloc need item from C bloc, 3 linked products
![image](https://github.com/Helfima/helmod/assets/20326713/71a76c18-4dd3-4571-b7ff-35d6fc60a90f)
When compute the C block, I solve the first A matrix, that take all inputs for objectives and I do same for each linked products but I use the first found product to create objectives
![image](https://github.com/Helfima/helmod/assets/20326713/13298113-8fa8-4274-bd0d-7d19bb82b970)
We can solve A matrix with all other matrix
![image](https://github.com/Helfima/helmod/assets/20326713/9ee24ccd-2db3-4450-a376-acfd57288c63)
After I report values C1, C2 and C3 in C matrix

**Comment by Helfima** [comment]
fixed v1.0.9

**Comment by SerhiyShamshetdinov** [comment]
It looks like there is still mistake is:
It counts the required amount of the product (made in White bulb block) much more than actually required. 
The grey bulb uses it outside and also product is used inside the white bulb block:

Required: 
0.06 inside White Bulb Block
0.06 inside Grey Bulb Block
= 0.12

Actually calculated to produce = 0.33
White Bulb Block exports 0.27 instead of minimum required 0.06 = 0.21 more

Top level usage and "export":
<img width="1792" alt="image" src="https://github.com/Helfima/helmod/assets/847062/380868ed-beb6-4670-99a3-bc1490631020">

White bulb block "export" and the product block:
<img width="1793" alt="image" src="https://github.com/Helfima/helmod/assets/847062/2835d854-aa7c-4a9a-8ea4-79ac0f4fb25f">

Usages of the product in White Bulb Block:
<img width="1786" alt="image" src="https://github.com/Helfima/helmod/assets/847062/ebd75c81-ca39-40a6-8f2d-b4ae7f72aafb">

Product block actually has 2 independent products (second one is correctly calculated but is used only inside White Bulb Block)
It was cleaned and shows the the same in both Matrix and Element Mode:
<img width="1793" alt="image" src="https://github.com/Helfima/helmod/assets/847062/fa607f20-579b-4ffd-8631-4e04497b9505">

**Comment by SerhiyShamshetdinov** [comment]
@Helfima but I actually tested this after copy-pasting my big tree to new one.
And I saw differences. It looks like it's copied partially (loses some properties when is pasted or when is copied).

At least it looses product "locked" property and the set amount of such product.

So fun that with above product in my primary tree everything is good)))
Minor overproduction in bounds of the error:
<img width="1793" alt="image" src="https://github.com/Helfima/helmod/assets/847062/367c3072-5aa8-453a-ab45-5560ce37beb1">

**Comment by SerhiyShamshetdinov** [comment]
Ok, another 2 products: 
1st is used only by the block at the root level (Grey Bulb)
**2nd is never used !!!**
Both products are produces in 1 block inside the White Bulb Block (so in 1 level of consumer block)

The strange thing is both products are calculated to the same amount (and fir the 1st 1 it is still wrong - with overproduction).
Looks like ones are linked to each other)

White Bulb screen where this block resides:
<img width="1788" alt="image" src="https://github.com/Helfima/helmod/assets/847062/c908d06e-6c01-44a4-831c-108ce4a0c016">

Inside the block where these products produced based on other common products:
<img width="1788" alt="image" src="https://github.com/Helfima/helmod/assets/847062/1c324230-ee67-4d7d-a6bd-2d9ca9bd1c9f">

Root level where White block exports these products and Grey Block consumes only 1st (2 pictures):
<img width="1784" alt="image" src="https://github.com/Helfima/helmod/assets/847062/a976d728-1e6c-4359-bbcf-8ebe6769ac23">
<img width="1783" alt="image" src="https://github.com/Helfima/helmod/assets/847062/284430f0-9a86-478c-988a-da348837170f">

Finally, after tree copy-pasting the general picture is the same but the common calculated amount is different (0.48 instead of 0.34):
<img width="1794" alt="image" src="https://github.com/Helfima/helmod/assets/847062/ea7ef440-59c4-4567-b4d8-0729a8b5c2c6">

Hope this will help :-)

**Comment by SerhiyShamshetdinov** [comment]
@Helfima 
you know, copy-pasting gives some clean position to validate features.
I'm afraid of some possible trash in my tree since it was started in the past version and we had several versions of v1.

But some new properties possibly are missed in tree copy or paste.

Good luck!
